from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass
class WorkflowTask:
    video_path: str
    subtitle_path: str
    intent: str
    out_dir: str
    run_id: str = "workflow_run"
    clip_count: int | None = None


@dataclass
class ClipPlanPolicy:
    task_type: str = "general"
    audience: str = "general viewers"
    output_goal: str = "first_cut_review_video"
    segment_count_policy: dict[str, Any] = field(
        default_factory=lambda: {
            "mode": "adaptive",
            "min_segments": 1,
            "max_segments": 5,
            "target_segments": None,
            "allow_less_than_target": True,
        }
    )
    duration_policy: dict[str, Any] = field(
        default_factory=lambda: {
            "min_segment_seconds": 20,
            "max_segment_seconds": 90,
            "target_segment_seconds": None,
            "target_final_duration_seconds": None,
            "max_final_duration_seconds": 180,
            "allow_shorter_if_quality_low": True,
        }
    )
    selection_policy: dict[str, Any] = field(
        default_factory=lambda: {
            "quality_first": True,
            "avoid_overlap": True,
            "avoid_repetition": True,
            "prefer_semantic_boundary": True,
            "min_cut_quality_score": 0.6,
            "prefer_dense_highlights": False,
        }
    )
    output_policy: dict[str, Any] = field(
        default_factory=lambda: {
            "generate_final_review": True,
            "generate_timeline": True,
            "generate_subtitle": True,
            "generate_review_sheet": True,
            "title_card": "optional",
            "transition": "none",
        }
    )
    required_content_goals: list[str] = field(default_factory=lambda: ["初高中物理的区别与联系", "高中物理学习内容或知识结构", "学习方法提醒"])
    optional_content_goals: list[str] = field(default_factory=lambda: ["典型例题", "易错点"])
    minimum_narrative_roles: list[str] = field(default_factory=lambda: ["introduction", "core_explanation", "method_or_example", "closing_or_summary"])
    reasoning_summary: str = "Adaptive policy generated by planner."

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


TaskPlan = ClipPlanPolicy


def normalize_task_plan(payload: dict[str, Any] | None, defaults: dict[str, Any] | None = None) -> dict[str, Any]:
    plan = ClipPlanPolicy().to_dict()
    defaults = defaults or {}
    if defaults:
        _deep_update(plan, defaults)
    if payload:
        _deep_update(plan, payload)
    plan["segment_count_policy"]["mode"] = "adaptive"
    plan["segment_count_policy"]["min_segments"] = int(plan["segment_count_policy"].get("min_segments") or 1)
    plan["segment_count_policy"]["max_segments"] = int(plan["segment_count_policy"].get("max_segments") or 5)
    target = plan["segment_count_policy"].get("target_segments")
    plan["segment_count_policy"]["target_segments"] = int(target) if target not in (None, "", 0) else None
    plan["duration_policy"]["min_segment_seconds"] = float(plan["duration_policy"].get("min_segment_seconds") or 20)
    plan["duration_policy"]["max_segment_seconds"] = float(plan["duration_policy"].get("max_segment_seconds") or 90)
    target_segment = plan["duration_policy"].get("target_segment_seconds")
    plan["duration_policy"]["target_segment_seconds"] = float(target_segment) if target_segment not in (None, "", 0) else None
    plan["duration_policy"]["max_final_duration_seconds"] = float(plan["duration_policy"].get("max_final_duration_seconds") or 180)
    plan["selection_policy"]["min_cut_quality_score"] = float(plan["selection_policy"].get("min_cut_quality_score") or 0.6)
    return plan


def _deep_update(base: dict[str, Any], extra: dict[str, Any]) -> None:
    for key, value in extra.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_update(base[key], value)
        else:
            base[key] = value

